# Python Objects

# Data types:

### Integers (int)

In [1]:
x = 1
y = 4

print(type(x))
print(type(y))

<class 'int'>
<class 'int'>


### Integer operations

In [2]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x /(x+y))

5
-3
4
0.25
0.2


### Floating-point numbers (float)


In [3]:
import numpy as np
x = 1.
y = 4.
z = np.pi

print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


### Floating-point operations

In [4]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x /(x+y))

5.0
-3.0
4.0
0.25
0.2


### Strings (str)

In [5]:
x = '1.'
y = '4.'
z = 'np.pi'

print(type(x))
print(type(y))
print(type(z))

<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
print(x + y) # This concatanates strings

1.4.


Sometimes is it advisable to delete the variables if you are re-using them for different data formats.

In [7]:
del x
del y
del z

## Complex numbers

In [8]:
z = -2 + 4j

print(z)

(-2+4j)


### Conjugate

In [9]:
zc = np.conj(z)

print(zc)

(-2-4j)


### Norm

In [10]:
normz = np.abs(z)

print(normz)

4.47213595499958


## Second manner

You can also use the complex() function.

In [11]:
z2 = complex(-2,4)

print(z2)

(-2+4j)


In [12]:
normz2 = np.abs(z2)

print(normz2)

4.47213595499958


# Python Objects

### Tuples

- A tuple is an ordered set of objects that cannot be manually changed.


- The objects inside a tuple can have different data formats.


In [58]:
# Example 1

tuple_1 = ('hola', 0, 1., 2)

print(tuple_1, type(tuple_1))

('hola', 0, 1.0, 2) <class 'tuple'>


We can also print individual elements in the tuple:

In [60]:
print(tuple_1[0]) # First element
print(tuple_1[::2]) # Jumping one element

hola
('hola', 1.0)


### Lists

- A list of is an ordered set of objects that can be manually changed.


- The objects can have different data types.

In [13]:
list_1 = ['hola', 1, 2., 3]

print(list_1)

['hola', 1, 2.0, 3]


## Accessing objects in a list

In [14]:
A0 = list_1[0]
A1 = list_1[1]
A2 = list_1[2]
A3 = list_1[3]

print(A0, type(A0))
print(A1, type(A1))
print(A2, type(A2))
print(A3, type(A3))

hola <class 'str'>
1 <class 'int'>
2.0 <class 'float'>
3 <class 'int'>


### Using a for loop

In [15]:
for i in list_1:
    print(i, type(i))

hola <class 'str'>
1 <class 'int'>
2.0 <class 'float'>
3 <class 'int'>


## Example: List

In [16]:
list_2 = [0,1,2,3,4,5,6,7,8,9]

We can select elements with [m, n].

In [61]:
A24 = list_2[2:4] # to n-1

print(A24, type(A24))

[2, 3] <class 'list'>


Also, we can use : to select all elements, e.g up to certain element position [:,n] or from certain element position [m:].

In [18]:
print(list_2[:5])
print(list_2[5:])

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]


- The length of a list can be returned with len()


- Similarly, the minimum number or maximum numbers in the list can be obtained with min() and max().

In [62]:
print(len(list_2))

print(min(list_2))

print(max(list_2))

10
1
15


Individual elements can be obtained with [::n], where n tells how many positions we jump

In [20]:
print(list_2[::2])

[0, 2, 4, 6, 8]


In [21]:
print(list_2[-1])

9


In [73]:
print(list_2[-2])

8


In [22]:
print(list_2[-2])

8


In [23]:
print(list_2[1:-1])

[1, 2, 3, 4, 5, 6, 7, 8]


In [24]:
list_2[0]=15
print(list_2)

[15, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [25]:
list_3 = list_1+list_2

In [26]:
list_3.append(100)

print(list_3)

['hola', 1, 2.0, 3, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100]


In [27]:
del list_3[0]

print(list_3)

[1, 2.0, 3, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100]


In [36]:
list_array = [[1,2,3,4],[5,6,7,8,9]]

print(list_array)

print(list_array[0], 'len =', len(list_array[0]))
print(list_array[1], 'len =', len(list_array[1]))

[[1, 2, 3, 4], [5, 6, 7, 8, 9]]
[1, 2, 3, 4] len = 4
[5, 6, 7, 8, 9] len = 5


In [40]:
print(list_array[0][0], 'type =', type(list_array[0][0]))
print(list_array[1][0], 'type =', type(list_array[0][0]))

1 type = <class 'int'>
5 type = <class 'int'>


In [41]:
print(list_array[0][:], 'type =', type(list_array[0][0]))
print(list_array[1][-1], 'type =', type(list_array[0][0]))

[1, 2, 3, 4] type = <class 'int'>
9 type = <class 'int'>


### Arrays


- Very useful when carrying out mathematical operations.


- Numpy needs to be called as Lists are the native Python objects.

In [68]:
A = np.array((10., 20., 50., 100., 80., 65.))

B = np.array([10., 20., 50., 100., 80., 65.])

print(A, type(A))
print(B, type(B))

[ 10.  20.  50. 100.  80.  65.] <class 'numpy.ndarray'>
[ 10.  20.  50. 100.  80.  65.] <class 'numpy.ndarray'>


### Dictionaries

In [49]:
dictionary_1 = {'variable x': 1,'variable y': 2}

print(dictionary_1, type(dictionary_1))

{'variable x': 1, 'variable y': 2} <class 'dict'>


In [50]:
dictionary_1['variable x']

1

In [51]:
dictionary_1['variable y']

2

### Defining dictionaries

In [53]:
dictionary_2={}

dictionary_2['temperature'] = [10, 40, 50, 60]
dictionary_2['pressure'] = (1, 1.6, 3, 4)

print(dictionary_2)

{'temperature': [10, 40, 50, 60], 'pressure': (1, 1.6, 3, 4)}


In [55]:
print(dictionary_2['temperature'], type(dictionary_2['temperature']))

[10, 40, 50, 60] <class 'list'>


In [56]:
print(dictionary_2['pressure'], type(dictionary_2['pressure']))

(1, 1.6, 3, 4) <class 'tuple'>


In [57]:
dictionary_2.keys()

dict_keys(['temperature', 'pressure'])

In [70]:
dictionary_3={}

dictionary_3['temperature'] = [10, 40, 50, 60]
dictionary_3['pressure'] = (1, 1.6, 3, 4)
dictionary_3['density'] = np.array((0.2, 0.4, 0.1, 0.3))

print(dictionary_3)

{'temperature': [10, 40, 50, 60], 'pressure': (1, 1.6, 3, 4), 'density': array([0.2, 0.4, 0.1, 0.3])}


In [72]:
print(dictionary_3['temperature'], type(dictionary_3['temperature']))
print(dictionary_3['pressure'], type(dictionary_3['pressure']))
print(dictionary_3['density'], type(dictionary_3['density']))

[10, 40, 50, 60] <class 'list'>
(1, 1.6, 3, 4) <class 'tuple'>
[0.2 0.4 0.1 0.3] <class 'numpy.ndarray'>
