# Gauss methods for linear equation systems

Solve systems of the type below for $x$ and $y$:

$ax + by = c$ 

$dx + ey = f$

## Example:

Solve:

$4x + 5y = -2$

$2x -3y = 1$ 


In [2]:
import matplotlib.pyplot as plt

import numpy as np

## 1. LU decomposition method:

## Example:

Solve:

$4x + 5y = -2$

$2x -3y = 1$ 

In [3]:
A = np.array([[4, 5], [2, -3]])

print(A)

[[ 4  5]
 [ 2 -3]]


In [4]:
b = np.array([[-2, 1]]).T

print(b)

[[-2]
 [ 1]]


### Use: 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html

In [5]:
import scipy.linalg  

In [6]:
P, L, U = scipy.linalg.lu(A)

In [7]:
print(P)

[[1. 0.]
 [0. 1.]]


In [8]:
print(L)

[[1.  0. ]
 [0.5 1. ]]


In [9]:
print(U)

[[ 4.   5. ]
 [ 0.  -5.5]]


In [10]:
A1 = P @ L @ U

print(A1)

[[ 4.  5.]
 [ 2. -3.]]


### Same system, different order:

$2x -3y = 1$ 

$4x + 5y = -2$



In [11]:
A2 = np.array([[2, -3], [4, 5]])

print(A2)

[[ 2 -3]
 [ 4  5]]


In [12]:
P2, L2, U2 = scipy.linalg.lu(A2)

In [13]:
print(P2)


[[0. 1.]
 [1. 0.]]


In [14]:
A2 = P2 @ L2 @ U2

print(A2)

[[ 2. -3.]
 [ 4.  5.]]


### Find the solution:

In [15]:
Linv = np.linalg.inv(L)

Uinv = np.linalg.inv(U)

In [16]:
print(Linv)

[[ 1.   0. ]
 [-0.5  1. ]]


In [17]:
print(Uinv)

[[ 0.25        0.22727273]
 [-0.         -0.18181818]]


In [18]:
y = Linv @ b

print(y)

[[-2.]
 [ 2.]]


In [19]:
x_sln = Uinv @ y

print(x_sln)

[[-0.04545455]
 [-0.36363636]]


## Example:

$4x + 3y + 2z = 25$

$3x -5y + 2z = -4$

$-2x + 2y + 3z = -10$

In [20]:
A = np.array([[4, 3, 2], [3, -5, 2], [-2, 2, 3]])

In [21]:
b = np.array([[25], [-4], [-10]])

print(b)

[[ 25]
 [ -4]
 [-10]]


In [23]:
P, L, U = scipy.linalg.lu(A)

In [24]:
print(P)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
print(L)

[[ 1.          0.          0.        ]
 [ 0.75        1.          0.        ]
 [-0.5        -0.48275862  1.        ]]


In [26]:
print(U)

[[ 4.          3.          2.        ]
 [ 0.         -7.25        0.5       ]
 [ 0.          0.          4.24137931]]


In [27]:
Linv = np.linalg.inv(L)
Uinv = np.linalg.inv(U)

print(Linv)
print(Uinv)

[[ 1.          0.          0.        ]
 [-0.75        1.          0.        ]
 [ 0.13793103  0.48275862  1.        ]]
[[ 0.25        0.10344828 -0.1300813 ]
 [-0.         -0.13793103  0.01626016]
 [ 0.          0.          0.23577236]]


In [28]:
yy = Linv @ b

print(yy)

[[ 25.        ]
 [-22.75      ]
 [ -8.48275862]]


In [29]:
xx_sln = Uinv @ yy

print(xx_sln)

[[ 5.]
 [ 3.]
 [-2.]]


## 2. Gauss elimination method:


Documentation: 

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter14.04-Solutions-to-Systems-of-Linear-Equations.html


Code reference:

https://www.delftstack.com/howto/python/gaussian-elimination-using-pivoting/


### Same example:

$4x + 3y + 2z = 25$

$3x -5y + 2z = -4$

$-2x + 2y + 3z = -10$

In [30]:
# Define matrix A
A = np.array([[4., 3., 2.], [3., -5., 2.], [-2., 2., 3.]])
 
# Define vector b
b = np.array([25., -4., -10.])

print("Solution using numpy:", np.linalg.solve(A, b))

Solution using numpy: [ 5.  3. -2.]


In [31]:
print(A)

[[ 4.  3.  2.]
 [ 3. -5.  2.]
 [-2.  2.  3.]]


In [32]:
# Solution using Gaussian elimination with pivoting.
# Based on: https://www.delftstack.com/howto/python/gaussian-elimination-using-pivoting/

# Length of vector b
n = len(b)

# Solution vector
x = np.zeros(n, float)

# first loop specifies the fixed row
for k in range(n - 1):
    
    # Compute the absolute values element-wise
    #print("value", np.fabs(A[k,k]))
    
    if np.fabs(A[k,k]) < 1.0e-12:
    
        for i in range(k + 1, n):
            
            if np.fabs(A[i,k]) > np.fabs(A[k,k]):
                
                A[[k,i]] = A[[i,k]]
                b[[k,i]] = b[[i,k]]
                
                break

    # Applies the elimination below the fixed row
    for i in range(k+1,n):
        
        if A[i,k] == 0:continue

        factor = A[k,k]/A[i,k]
        
        for j in range(k,n):
            A[i,j] = A[k,j] - A[i,j]*factor
            
            #we also calculate the b vector of each row
            
        b[i] = b[k] - b[i]*factor

print("Triangular matrix is: \n", A)

print("New Vector b is: \n", b)

Triangular matrix is: 
 [[  4.           3.           2.        ]
 [  0.           9.66666667  -0.66666667]
 [  0.           0.         -11.71428571]]
New Vector b is: 
 [25.         30.33333333 23.42857143]


In [33]:
# Update x vector
x[n-1] = b[n-1] / A[n-1, n-1]

print(x)

# Solve equations in triangular matrix:

for i in range(n-2, -1, -1):
    
    sum_ax = 0
  
    for j in range(i+1, n):
        sum_ax += A[i,j] * x[j]
        
    x[i] = (b[i] - sum_ax) / A[i,i]

print("The solution of the system is:", x)

[ 0.  0. -2.]
The solution of the system is: [ 5.  3. -2.]


## 3. Gauss-Jordan Method:


Documentation: 

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter14.04-Solutions-to-Systems-of-Linear-Equations.html

Code reference:

https://steemit.com/hive-181430/@sheham-sh/siz-tutorial-or-or-gauss-jordan-method-in-python-without-numpy-or-or-20-to-siz-official-or-or-by-sheham-sh

### Same example:

$4x + 3y + 2z = 25$

$3x -5y + 2z = -4$

$-2x + 2y + 3z = -10$

In [34]:
# First get augmented matrix

A_g = [
    [4, 3, 2, 25],
    [3, -5, 2, -4],
    [-2, 2, 3, -10]]

ini_array = np.array(A_g)

print("Initial array is:\n", ini_array)

Initial array is:
 [[  4   3   2  25]
 [  3  -5   2  -4]
 [ -2   2   3 -10]]


In [35]:
# Based on: https://steemit.com/hive-181430/@sheham-sh/siz-tutorial-or-or-gauss-jordan-method-in-python-without-numpy-or-or-20-to-siz-official-or-or-by-sheham-sh

# Get ones in diagonal:

def getone(pp, sd):
    """
    Function to loop over matrix elements, check if =1, and makes 1 if not.
    Get ones in the diagonal.
    """
    
    for i in range(len(sd[0])):
        # Check when =1
        if sd[pp][pp] != 1:
            q00 = sd[pp][pp]
            
            # Get 1's
            for j in range(len(sd[0])):
                sd[pp][j] = sd[pp][j] / q00

# Get zeroes outside the diagonal:

def getzero(r, c, sd):
    """
    Function to loop over matrix elements, and reduce non-diagonal elements to 0.
    Get zeroes outside the diagonal.
    """
    
    for i in range(len(sd[0])):
        
        if sd[r][c] != 0:
            q04 = sd[r][c]
    
            for j in range(len(sd[0])):
                sd[r][j] = sd[r][j] - ((q04) * sd[c][j])

In [36]:
# Loop over elements and call function defined above.

for i in range(len(A_g)):
    getone(i, A_g)

    for j in range(len(A_g)):
        if i != j:
            getzero(j, i, A_g)

sln_array = np.array(A_g)
print(A_g)
print("Gauss-Jordan Solution is:", sln_array[:,3])

[[1.0, 0.0, 0.0, 5.0], [0.0, 1.0, 0.0, 3.0], [0.0, 0.0, 1.0, -2.0]]
Gauss-Jordan Solution is: [ 5.  3. -2.]


## 4. Gauss-Seidel Method

The Gauss-Seidel Method is a specific iterative method, that is always using the latest estimated value for each elements in 𝑥. 

Documentation and code reference:

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter14.04-Solutions-to-Systems-of-Linear-Equations.html

### Same example:

$4x + 3y + 2z = 25$

$3x -5y + 2z = -4$

$-2x + 2y + 3z = -10$

In [37]:
# Define A matrix
a_lhs = np.array([[4., 3., 2.], [3., -5., 2.], [-2., 2., 3.]])

# Define b vector
b_rhs = np.array([25, -4, -10])

sln = np.linalg.solve(a_lhs, b_rhs)
print("Solution by NumPy:")
#print(np.linalg.solve(AA, BB))
print(sln)

Solution by NumPy:
[ 5.  3. -2.]


In [38]:
# Find diagonal coefficients
diag = np.diag(np.abs(a_lhs)) 

# Find row sum without diagonal
off_diag = np.sum(np.abs(a_lhs), axis=1) - diag 

if np.all(diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('NOT diagonally dominant')

NOT diagonally dominant


In [44]:
# Provide guesses
x1 = 0. # x0
x2 = 0. # y0
x3 = 0. # z0

# Define the threshold
epsilon = 1.e-8
converged = False

# Set an array containing our guessed solutions
x_old = np.array([x1, x2, x3]) # our guess

In [45]:
print('Iteration results')
print(' k,    x,     y,     z,     d')
print("%d, %.4f, %.4f, %.4f, %.4f"%(0, x1, x2, x3, 100))

for k in range(1, 50):
    
    x1 = (25 - 3*x2 - 2*x3)/4
    x2 = (4 + 3*x1 + 2*x3)/5
    x3 = (-10 +2*x1 - 2*x2)/3
    
    x = np.array([x1, x2, x3])
    
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x - x_old, x - x_old))
    
    print("%d, %.4f, %.4f, %.4f, %.9f"%(k, x1, x2, x3, dx))
    
    
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
    
        # assign the latest x value to the old value
    x_old = x
    
if not converged:
    print('Not converge, increase the # of iterations')

Iteration results
 k,    x,     y,     z,     d
0, 0.0000, 0.0000, 0.0000, 100.0000
1, 6.2500, 4.5500, -2.2000, 8.037723558
2, 3.9375, 2.2825, -2.2300, 3.238844315
3, 5.6531, 3.2999, -1.7645, 2.048197081
4, 4.6573, 2.8886, -2.1542, 1.145673989
5, 5.1606, 3.0347, -1.9161, 0.575629234
6, 4.9320, 2.9928, -2.0405, 0.263680302
7, 5.0257, 2.9992, -1.9823, 0.110465353
8, 4.9918, 3.0021, -2.0069, 0.041964802
9, 5.0019, 2.9984, -1.9977, 0.014184255
10, 5.0001, 3.0010, -2.0006, 0.004326083
11, 4.9996, 2.9995, -2.0000, 0.001685901
12, 5.0004, 3.0002, -1.9999, 0.001067197
13, 4.9998, 2.9999, -2.0001, 0.000669167
14, 5.0001, 3.0000, -1.9999, 0.000371065
15, 4.9999, 3.0000, -2.0000, 0.000185096
16, 5.0000, 3.0000, -2.0000, 0.000084231
17, 5.0000, 3.0000, -2.0000, 0.000035048
18, 5.0000, 3.0000, -2.0000, 0.000013209
19, 5.0000, 3.0000, -2.0000, 0.000004423
20, 5.0000, 3.0000, -2.0000, 0.000001347
21, 5.0000, 3.0000, -2.0000, 0.000000548
22, 5.0000, 3.0000, -2.0000, 0.000000352
23, 5.0000, 3.0000, -2.

## Example:

Solve:

$8x+3y-3z=14$

$-2x+8y+5z=5$

$3x+5y+10z=-8$

In [46]:

AA = np.array([[8, 3, -3], [-2, 8, 5], [3, 5, 10]], float)
#the b matrix constant terms of the equations 
BB = np.array([14, 5, -8], float)


sln = np.linalg.solve(AA, BB)
print("Solution by NumPy:")
#print(np.linalg.solve(AA, BB))
print(sln)

Solution by NumPy:
[ 0.36012365  1.86553323 -1.84080371]


In [47]:
a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]

# Find diagonal coefficients
diag = np.diag(np.abs(a)) 

# Find row sum without diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag 

if np.all(diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('NOT diagonally dominant')

matrix is diagonally dominant


In [48]:
x1 = 0
x2 = 0
x3 = 0

epsilon = 1e-10
converged = False

x_old = np.array([x1, x2, x3]) # my guess

print('Iteration results')
print(' k,    x1,     x2,     x3')

Iteration results
 k,    x1,     x2,     x3


In [49]:
for k in range(1, 50):
    x1 = (14 - 3*x2 + 3*x3)/8
    x2 = (5 + 2*x1 - 5*x3)/8
    x3 = (-8 -3*x1 - 5*x2)/10
    x = np.array([x1, x2, x3])
    
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x - x_old, x - x_old))
    
    print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    
    
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
    
        # assign the latest x value to the old value
    x_old = x
    
if not converged:
    print('Not converge, increase the # of iterations')

1, 1.7500, 1.0625, -1.8562
2, 0.6555, 1.9490, -1.9712
3, 0.2799, 1.9270, -1.8475
4, 0.3346, 1.8633, -1.8320
5, 0.3642, 1.8611, -1.8398
6, 0.3622, 1.8654, -1.8414
7, 0.3600, 1.8658, -1.8409
8, 0.3600, 1.8656, -1.8408
9, 0.3601, 1.8655, -1.8408
10, 0.3601, 1.8655, -1.8408
11, 0.3601, 1.8655, -1.8408
12, 0.3601, 1.8655, -1.8408
13, 0.3601, 1.8655, -1.8408
14, 0.3601, 1.8655, -1.8408
15, 0.3601, 1.8655, -1.8408
16, 0.3601, 1.8655, -1.8408
17, 0.3601, 1.8655, -1.8408
18, 0.3601, 1.8655, -1.8408
19, 0.3601, 1.8655, -1.8408
20, 0.3601, 1.8655, -1.8408
Converged!
