# Data types and Python objects

# A) Data types:

### Integers (int)

In [1]:
x = 1
y = 4

print(type(x))
print(type(y))

<class 'int'>
<class 'int'>


### Integer operations

In [2]:
print(x + y, type(x + y))
print(x - y, type(x - y))
print(x * y, type(x * y))
print(x / y, type(x / y))
print(x / (x + y), type(x / (x + y)))

# Note that the first three output numbers are still integers, while the latter three are floats.

5 <class 'int'>
-3 <class 'int'>
4 <class 'int'>
0.25 <class 'float'>
0.2 <class 'float'>


### Floating-point numbers (floats)


In [3]:
import numpy as np
x = 1.
y = 4.
z = np.pi

print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


### Floating-point operations

In [4]:
# All the operations return floating point numbers.
# If you are doing mathematical operations, it is generally advisable to use floats

print(x + y, type(x + y))
print(x - y, type(x - y))
print(x * y, type(x * y))
print(x / y, type(x / y))
print(x / (x + y), type(x / (x + y)))

5.0 <class 'float'>
-3.0 <class 'float'>
4.0 <class 'float'>
0.25 <class 'float'>
0.2 <class 'float'>


### Strings (str)

In [5]:
x = '1.'
y = '4.'
z = 'np.pi'

print(type(x))
print(type(y))
print(type(z))

<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
print(x + z) # This concatanates strings

1.np.pi


Sometimes is it advisable to delete the variables if you are re-using them for different data formats.

In [7]:
del x
del y
del z

## Complex numbers

"j" can be used as "i" to define complex numbers.

In [8]:
z = -2 + 4j

print(z)

(-2+4j)


### Conjugate

- You can use np.conj()


- See the documentation here:
https://numpy.org/doc/stable/reference/generated/numpy.conj.html

In [9]:
zc = np.conj(z)

print(zc)

(-2-4j)


### Norm

In [10]:
normz = np.abs(z)

print(normz, ', which is the same as:', np.sqrt(z.real**2 + z.imag**2))

# Note that you can access the real and imaginary parts of a number with z.real and z.imag.

4.47213595499958 , which is the same as: 4.47213595499958


## Second manner

You can also use the complex() function.

In [11]:
z2 = complex(-2,4)

print(z2)

(-2+4j)


In [12]:
normz2 = np.abs(z2)

print(normz2)

4.47213595499958


# B) Python Objects

## Tuples

- A tuple is an ordered set of objects that cannot be manually changed.


- The objects inside a tuple can have different data formats.


- Tuples are explicitly defined with **( )**


In [13]:
# Example 1

tuple_1 = ('hola', 0, 1., 2)

print(tuple_1, type(tuple_1))

('hola', 0, 1.0, 2) <class 'tuple'>


We can also print individual elements in the tuple:

In [14]:
print(tuple_1[0]) # First element

print(tuple_1[::2]) # Jumping one element

hola
('hola', 1.0)


Can we alter an element in the tuple?

Answer: No, we get an error.

In [15]:
#tuple[0] = 4.0 # Uncomment to see the error

## Lists

- A list of is an ordered set of objects that can be manually changed.


- The objects can have different data types.


- Lists are explicitly defined with **[ ]**.

In [16]:
list_1 = ['hola', 1, 2., 3]

print(list_1)

['hola', 1, 2.0, 3]


### Accessing objects in a list

In [17]:
A0 = list_1[0]
A1 = list_1[1]
A2 = list_1[2]
A3 = list_1[3]

print(A0, type(A0))
print(A1, type(A1))
print(A2, type(A2))
print(A3, type(A3))

hola <class 'str'>
1 <class 'int'>
2.0 <class 'float'>
3 <class 'int'>


### Using a for loop

In [18]:
for i in list_1:
    print(i, type(i))

hola <class 'str'>
1 <class 'int'>
2.0 <class 'float'>
3 <class 'int'>


### Example: List

In [19]:
list_2 = [0,1,2,3,4,5,6,7,8,9]

We can select elements with [m, n].

In [20]:
A24 = list_2[2:4] # to n-1

print(A24, type(A24))

[2, 3] <class 'list'>


Also, we can use : to select all elements, e.g up to certain element position [:,n] or from certain element position [m:].

In [21]:
print(list_2[:5])
print(list_2[5:])

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]


- The length of a list can be returned with len()


- Similarly, the minimum number or maximum numbers in the list can be obtained with min() and max().

In [22]:
print(len(list_2))

print(min(list_2))

print(max(list_2))

10
0
9


Individual elements can be obtained with [::n], where n tells how many positions we jump

In [23]:
print(list_2[::2])

[0, 2, 4, 6, 8]


We can print the last and second last elements:

In [24]:
print(list_2[-1])

9


In [25]:
print(list_2[-2])

8


Or, all the elements except the first and last on the list:

In [26]:
print(list_2[1:-1])

[1, 2, 3, 4, 5, 6, 7, 8]


And, we can also alter the list by changing certain elements:

In [27]:
list_2[0]=15
print(list_2)

[15, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Lists can also be concatenated with +

Be careful, because the + operation concatenates lists. 

It does not add numbers in the lists.

If you want to do operations, use arrays.

In [28]:
list_3 = list_1 + list_2

In [29]:
list_3.append(100)

print(list_3)

['hola', 1, 2.0, 3, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100]


### Delete elements from a list

In [30]:
del list_3[0]

print(list_3)

[1, 2.0, 3, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 100]


### Nested lists

A list can contain sub-lists as elements.

In [31]:
list_nest = [[1,2,3,4],[5,6,7,8,9]]

print(list_nest)

print(list_nest[0], 'len =', len(list_nest[0]))
print(list_nest[1], 'len =', len(list_nest[1]))

[[1, 2, 3, 4], [5, 6, 7, 8, 9]]
[1, 2, 3, 4] len = 4
[5, 6, 7, 8, 9] len = 5


### Accessing nested elements within a list

In [32]:
print(list_nest[0][0], 'type =', type(list_nest[0][0])) # First element of first sublist

print(list_nest[1][0], 'type =', type(list_nest[1][0])) # First element of second sublist

1 type = <class 'int'>
5 type = <class 'int'>


In [33]:
print(list_nest[0][:], 'type =', type(list_nest[0][0]))
print(list_nest[1][-1], 'type =', type(list_nest[0][0]))

[1, 2, 3, 4] type = <class 'int'>
9 type = <class 'int'>


## (Numpy) Arrays


- They are very useful when carrying out mathematical operations.


- Numpy needs to be called. remeber that lists are the native Python objects.


- np.array() converts Python objects into arrays

In [34]:
# Let's convert a tuple into an array:
A = np.array((10., 20., 50., 100., 80., 65.))


# Let's convert a list into an array:
B = np.array([10., 20., 50., 100., 80., 65.])

print(A, type(A))
print(B, type(B))

# As you can see, both return the same array

[ 10.  20.  50. 100.  80.  65.] <class 'numpy.ndarray'>
[ 10.  20.  50. 100.  80.  65.] <class 'numpy.ndarray'>


## Dictionaries

- They are objects that can contain sub-objects of different types.


- A "key" is used to identify each sub-object.

### Example 1:

In [35]:
dictionary_1 = {'variable x': 1,'variable y': 2}

print(dictionary_1, type(dictionary_1))

{'variable x': 1, 'variable y': 2} <class 'dict'>


Let us call individual objects:

In [36]:
dictionary_1['variable x']

1

In [37]:
dictionary_1['variable y']

2

### Defining dictionaries

### Example 2:

In [38]:
# Create an empty dictionary:

dictionary_2={ }

# Fill in the empty dictionary with two objects:

dictionary_2['temperature'] = [10, 40, 50, 60]   # The 1st object is a list
dictionary_2['pressure'] = (1, 1.6, 3, 4)   # The 2nd object is a tuple

print(dictionary_2)

{'temperature': [10, 40, 50, 60], 'pressure': (1, 1.6, 3, 4)}


In [39]:
print(dictionary_2['temperature'], type(dictionary_2['temperature']))

[10, 40, 50, 60] <class 'list'>


In [40]:
print(dictionary_2['pressure'], type(dictionary_2['pressure']))

(1, 1.6, 3, 4) <class 'tuple'>


The function **keys()** can be used to see which keys are defined within a dictionary:

In [41]:
dictionary_2.keys()

dict_keys(['temperature', 'pressure'])

### Example 3:

In [42]:
dictionary_3={}

dictionary_3['temperature'] = [10, 40, 50, 60]  # This is a list
dictionary_3['pressure'] = (1, 1.6, 3, 4)  # This is a tuple
dictionary_3['density'] = np.array((0.2, 0.4, 0.1, 0.3)) # This is an array

print(dictionary_3)

{'temperature': [10, 40, 50, 60], 'pressure': (1, 1.6, 3, 4), 'density': array([0.2, 0.4, 0.1, 0.3])}


In [43]:
print(dictionary_3['temperature'], type(dictionary_3['temperature']))
print(dictionary_3['pressure'], type(dictionary_3['pressure']))
print(dictionary_3['density'], type(dictionary_3['density']))

[10, 40, 50, 60] <class 'list'>
(1, 1.6, 3, 4) <class 'tuple'>
[0.2 0.4 0.1 0.3] <class 'numpy.ndarray'>
